---

- name: Install python-setup tools
  yum:
   name: python-setuptools
   state: present

#- name: Install pymysql
#  yum:
#   name: python-PyMySQL
#   state: present
#
#- name: Install Pip
#  yum:
#   name: pip
#   state: present 

- name: Make sure pymysql os present
  become: true #Needed if the other tasks are not played as root
  yum: 
   name: python-PyMySQL
   state: present

- name: Copy MySQL file config
  template:
   src: my.cnf.j2
   dest: "{{ mysql_default_config_file }}"
   owner: root
   group : root
   mode: 0644
  notify: restart mysql

- name: Create datadir if it does not exist
  file:
    path: "{{ mysql_datadir }}"
    state: directory
    owner: mysql
    group: mysql
    mode: 0755
